<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Pokemon store</title>
</head>

<style>
    * {
        margin: 0;
        padding: 0;
        box-sizing: border-box;
    }

    body {
        font-family: "Poppins", sans-serif;

    }

    .navbar {
        display: flex;
        align-items: center;
        padding: 20px;
    }

    nav {
        flex: 1;
        text-align: right;
    }

    nav ul {
        display: inline-block;
        list-style-type: none;
    }

    nav ul li {
        display: inline-block;
        margin-right: 20px;
    }

    a {
        text-decoration: none;
        color: #555;
    }

    p {
        color: #555;
    }

    .container {
        max-width: 1300px;
        margin: auto;
        padding-left: 25px;
        padding-right: 25px;
    }

    .row {
        display: flex;
        align-items: center;
        flex-wrap: wrap;
        justify-content: space-around;
    }

    .col-2 {
        flex-basis: 50%;
        min-width: 300px;
    }

    .col-2 img {
        max-width: 100%;
        padding: 50px 0;
    }

    .col-2 h1 {
        font-size: 50px;
        line-height: 60px;
        margin: 25px 0;
    }

    .btn {
        display: inline-block;
        background: #ff523b;
        color: #ffffff;
        padding: 8px 30px;
        margin: 30px 0;
        border-radius: 30px;
        transition: background 0.5s;
    }

    .btn:hover {
        background: #563434;
    }

    .header {
        background: radial-gradient(#fff, #ffd6d6);
    }

    .header .row {
        margin-top: 70px;
    }

    .col-3 img {
        width: 100%;
    }

    .small-container {
        max-width: 1080px;
        margin: auto;
        padding-left: 25px;
        padding-right: 25px;
    }

    .col-4 {
        flex-basis: 25%;
        padding: 10px;
        min-width: 200px;
        margin-bottom: 50px;
        transition: transform 0.5s;
    }

    .col-4 .product-description {
        min-height: 135px;
    }

    .col-4 img {
        width: 100%;
    }

    .col-4 p {
        font-size: 14px;
    }

    .title {
        text-align: center;
        margin: 0 auto 80px;
        position: relative;
        line-height: 60px;
        color: #555;
    }

    .title::after {
        content: "";
        background: #ff523b;
        width: 80px;
        height: 5px;
        border-radius: 5px;
        position: absolute;
        bottom: 0;
        left: 50%;
        transform: translate(-50%);
    }

    h4 {
        color: #555;
        font-weight: normal;
    }


    .rating .fas {
        color: #ff523b;
    }

    .rating .far {
        color: #ff523b;
    }

    .col-4:hover {
        transform: translateY(-5px);
    }

    .col-2 .offer-img {
        padding: 50px;
    }

    small {
        color: #555;
    }

    .brands {
        margin: 100px auto;
    }

    .col-5 {
        width: 160px;
    }

    .col-5 img {
        width: 100%;
        cursor: pointer;
        filter: grayscale(100%);
    }

    .col-5 img:hover {
        width: 100%;
        cursor: pointer;
        filter: grayscale(0);
    }

    /* footer */

    .footer {
        background: #000;
        color: #8a8a8a;
        font-size: 14px;
        padding: 60px 0 20px;
    }

    .footer p {
        color: #8a8a8a;
    }

    .footer h3 {
        color: #ffffff;
        margin-bottom: 20px;
    }

    .footer-col-1,
    .footer-col-2,
    .footer-col-3,
    .footer-col-4 {
        min-width: 250px;
        margin-bottom: 20px;
    }

    .footer-col-1 {
        flex-basis: 30%;
    }

    .footer-col-2 {
        flex: 1;
        text-align: center;
    }

    .footer-col-2 img {
        width: 180px;
        margin-bottom: 20px;
    }

    .footer-col-3,
    .footer-col-4 {
        flex-basis: 12%;
        text-align: center;
    }

    ul {
        list-style-type: none;
    }

    .app-logo {
        margin-top: 20px;
    }

    .app-logo img {
        width: 140px;
    }

    .footer hr {
        border: none;
        background: #b5b5b5;
        height: 1px;
        margin: 20px 0;
    }

    .copyright {
        text-align: center;
    }

    .menu-icon {
        width: 28px;
        margin-left: 20px;
        display: none;
    }

    /* media query for menu */

    @media only screen and (max-width: 800px) {
        nav ul {
            position: absolute;
            top: 70px;
            left: 0;
            background: #333;
            width: 100%;
            overflow: hidden;
            transition: max-height 0.5s;
        }

        nav ul li {
            display: block;
            margin-right: 50px;
            margin-top: 10px;
            margin-bottom: 10px;
        }

        nav ul li a {
            color: #fff;
        }

        .menu-icon {
            display: block;
            cursor: pointer;
        }
    }

    /* all products page */

    select {
        border: 1px solid #ff523b;
        padding: 5px;
    }

    select:focus {
        outline: none;
    }

    .page-btn span {
        display: inline-block;
        border: 1px solid #ff523b;
        margin-left: 10px;
        width: 40px;
        height: 40px;
        text-align: center;
        line-height: 40px;
        cursor: pointer;
    }

    .page-btn span:hover {
        background: #ff523b;
        color: #ffffff;
    }

    .single-product .col-2 img {
        padding: 0;
    }

    .single-product .col-2 {
        padding: 20px;
    }

    .single-product h4 {
        margin: 20px 0;
        font-size: 22px;
        font-weight: bold;
    }

    .single-product select {
        display: block;
        padding: 10px;
        margin-top: 20px;
    }

    .single-product input {
        width: 50px;
        height: 40px;
        padding-left: 10px;
        font-size: 20px;
        margin-right: 10px;
        border: 1px solid #ff523b;
    }

    input:focus {
        outline: none;
    }

    .single-product .fas {
        color: #ff523b;
        margin-left: 10px;
    }

    table {
        width: 100%;
        border-collapse: collapse;
    }

    th {
        text-align: left;
        padding: 5px;
        color: #ffffff;
        background: #ff523b;
        font-weight: normal;
    }

    td {
        padding: 10px 5px;
    }

    td input {
        width: 40px;
        height: 30px;
        padding: 5px;
    }

    td a {
        color: #ff523b;
        font-size: 12px;
    }

    td img {
        width: 80px;
        height: 80px;
        margin-right: 10px;
    }

    .total-price {
        display: flex;
        justify-content: flex-end;
    }

    .total-price table {
        border-top: 3px solid #ff523b;
        width: 100%;
        max-width: 400px;
    }

    td:last-child {
        text-align: right;
    }

    th:last-child {
        text-align: right;
    }

    /* account page */
    .account-page {
        padding: 50px 0;
        background: radial-gradient(#fff, #ffd6d6);
    }

    .form-container {
        background: #ffffff;
        width: 300px;
        height: 400px;
        position: relative;
        text-align: center;
        padding: 20px 0;
        margin: auto;
        box-shadow: 0 0 20px 0px rgba(0, 0, 0, 0.1);
        overflow: hidden;
    }

    .form-container span {
        font-weight: bold;
        padding: 0 10px;
        color: #555555;
        cursor: pointer;
        width: 100px;
        display: inline-block;
    }

    .form-btn {
        display: inline-block;
    }

    .form-container form {
        max-width: 300px;
        padding: 0 20px;
        position: absolute;
        top: 130px;
        transition: transform 1s;
    }



    form input {
        width: 100%;
        height: 30px;
        margin: 10px 0;
        padding: 0 10px;
        border: 1px solid #ccc;
    }

    form .btn {
        width: 100%;
        border: none;
        cursor: pointer;
        margin: 10px 0;
    }

    form .btn:focus {
        outline: none;
    }

    #LoginForm {
        left: -300px;
    }

    #RegForm {
        left: 0;
    }

    form a {
        font-size: 12px;
    }

    #Indicator {
        width: 100px;
        border: none;
        background: #ff523b;
        height: 3px;
        margin-top: 8px;
        transform: translateX(100px);
        transition: transform 1s;
    }

    /* media query for less than 600 screen size */

    @media only screen and (max-width: 600px) {
        .row {
            text-align: center;
        }

        .col-2,
        .col-3,
        .col-4 {
            flex-basis: 100%;
        }

        .single-product .row {
            text-align: left;
        }

        .single-product .col-2 {
            padding: 20px 0;
        }

        .single-product h1 {
            font-size: 26px;
            line-height: 32px;
        }

        .cart-info p {
            display: none;
        }
    }
    * {
        margin: 0;
        padding: 0;
        box-sizing: border-box;
        font-family: "Nunito", sans-serif;
    }

    h1 {
        font-size: 16px;
        margin: 5px;
    }
    .cart_container {
        width: 100%;
        height: 92vh;
        display: flex;
        justify-content: space-evenly;
        align-items: center;
        background-color: #f9fafc;
    }

    /*
    Payment Information card
    */
    .details_card {
        width: 700px;
        height: 400px;
        box-shadow: 0 0 5px 0 rgba(0, 0, 0, 0.2);
        border-radius: 8px;
        padding: 10px;
        background-color: #fff;
    }

    /*
    Order Summary Card
    */
    .summary_card {
        background-color: #fff;
        min-width: 640px;
        min-height: 400px;
        max-width: 110vh;
        box-shadow: 0 0 5px 0 rgba(0, 0, 0, 0.2);
        border-radius: 8px;
        padding: 10px;
    }

    /*
    Order Card Item Card
    */
    .card_item {
        display: flex;
        position: relative;
        margin: 10px 0;
    }
    .close-btn {
        position: absolute;
        right: 10px;
        top: 5px;
    }

    .card_item .product_img img {
        height: 80px;
        margin-right: 20px;
        width: 70px;
        border-radius: 5px;
    }

    .product_info {
        width: 100%;
    }
    .product_info h1 {
        font-size: 20px;
        color: #1e212d;
        margin: 5px 0;
    }

    .product_info p {
        color: #a1a1a1;
        font-size: 14px;
    }
    .product_rate_info {
        display: flex;
        flex-direction: column;
        margin: 5px 0;
        align-items: flex-end;
        justify-content: end;
    }
    .product_minus_plus {
        display: flex;
        flex-direction: row
        margin: 5px 0;
        align-items: center
    }
    .product_minus_plus .btn {
        width: 60px;
        height: 30px;
        background-color:#b5b5b5;
    }
    /*
    cart item + & -
    */
    .pqt {
        font-size: 20px;
        line-height: 30px;
        width: 30px;
        text-align: center;
    }

    .pqt-plus,
    .pqt-minus {
        background: #fcfcfc;
        border: none;
        font-size: 20px;
        height: 100%;
        padding: 0 15px;
    }
    .pqt-plus:hover,
    .pqt-minus:hover {
        background: #53b5aa;
        color: #fff;
        cursor: pointer;
    }

    .pqt-plus {
        line-height: 30px;
    }

    .pqt-minus {
        line-height: 30px;
    }
    /*
    Order price & total
    */
    .order_price,
    .order_service,
    .order_total {
        display: flex;

        justify-content: space-between;
        padding: 10px;
    }
    .order_price p,
    .order_service p {
        color: #a1a1a1;
    }

    .order_total p {
        font-weight: 600;
    }

    /*
    Payment Information all input
    */

    input {
        outline: 0;
        background: #f2f2f2;
        border-radius: 4px;
        width: 100%;
        border: 0;
        caret-color: #4f5d7e;
        margin: 10px 15px;
        padding: 15px 20px;
        box-sizing: border-box;
        font-size: 14px;
    }

    .first_lastName,
    .shipping_card,
    .address {
        display: flex;
        justify-content: space-between;
        margin: 10px 0;
    }

    .new_card {
        width: 100%;
        height: 100px;
        border: 2px solid #53b5aa;
        padding: 10px;
        margin: 10px;
        border-radius: 10px;
    }

    .add_savedcard {
        width: 100%;
        height: 100px;
        border: 2px solid #a1a1a1;
        padding: 10px;
        margin: 10px;
        border-radius: 10px;
    }
    /*
    Procced Payment button
    */
    .proced_payment a {
        padding: 10px 20px;
        width: 200px;
        border: 2px solid #f5f5f5;
        background-color: #53b5aa;
        color: #000;
        margin-left: 10px;
        cursor: pointer;
        text-decoration: none;
    }
</style>


<!-- Header Section -->
<header>
    <div class="header">
        <div class="container">
            <div class="navbar">
                <div class="logo">
                    <a href="home"><img src="/assets/images/pokeball-png-45353.png" alt="RedStore" width="50px"> </a>
                </div>
                <nav>
                    <ul id="MenuItems">
                        <li><a href="home">Home</a></li>
                        <li><a href="">Products</a></li>
                        <li><a href="">About</a></li>
                        <li><a href="">Contact</a></li>
                        <li><a href="">Account</a></li>
                    </ul>
                </nav>
                <a href="cart"><img src="https://i.ibb.co/PNjjx3y/cart.png" alt="burger" width="30px"
                                    height="30px"/></a>
                <img src="https://i.ibb.co/6XbqwjD/menu.png" alt="" class="menu-icon" onclick="menutoggle()"/>
            </div>
        </div>
    </div>

</header>

<body>
    <div class="small-container">
        <div class="order_summary">
            <h1>Ваша корзина</h1>
            <div class="summary_card">
                <?php if (isset($cartProducts)) {
                    foreach ($cartProducts as $el): ?>
                        <div class="card_item">
                            <div class="product_img">
                                <img src="<?= $el["image"]; ?>" alt="<?= $el["title"]; ?>" />
                            </div>
                            <div class="product_info">
                                <h1><?= $el["title"]; ?></h1>
                                <p><?= $el["description"]; ?></p>
                                <div class="close-btn">
                                    <i class="fa fa-close"></i>
                                </div>
                                <div class="product_rate_info">
                                    <h1><?= $el["total"]; ?> ₽</h1>
                                    <div class="product_minus_plus">
                                        <form action="/remove-product" method="POST">
                                            <button type="submit" class="btn" name="decProductToCart" value="<?=$el['product_id']?>">-</button>
                                        </form>
                                        <span class="pqt"><?= $el["count"]; ?></span>
                                        <form action="/add-one-product" method="POST">
                                            <button type="submit" class="btn" name="incProductToCart" value="<?=$el['product_id']?>">+</button>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    <?php endforeach;
                } ?>

                <hr />
                <div class="order_total">
                    <p>Стоимость всей корзины</p>
                    <h2><?php if (isset($cartTotal[0])) echo $cartTotal[0] ?> ₽</h2>
                </div>
            </div>
        </div>
    </div>

<div class="footer">
    <div class="container">
        <div class="row">
            <div class="footer-col-1">
                <h3>Download Our App</h3>
                <p>Download App for Android and iso mobile phone.</p>
                <div class="app-logo">
                    <img src="https://i.ibb.co/KbPTYYQ/play-store.png" alt=""/>
                    <img src="https://i.ibb.co/hVM4X2p/app-store.png" alt=""/>
                </div>
            </div>

            <div class="footer-col-2">
                <img src="https://i.ibb.co/j3FNGj7/logo-white.png" alt=""/>
                <p>
                    Our Purpose Is To Sustainably Make the Pleasure and Benefits of
                    Sports Accessible to the Many.
                </p>
            </div>

            <div class="footer-col-3">
                <h3>Useful Links</h3>
                <ul>
                    <li>Coupons</li>
                    <li>Blog Post</li>
                    <li>Return Policy</li>
                    <li>Join Affiliate</li>
                </ul>
            </div>

            <div class="footer-col-4">
                <h3>Follow us</h3>
                <ul>
                    <li>Facebook</li>
                    <li>Twitter</li>
                    <li>Instagram</li>
                    <li>YouTube</li>
                </ul>
            </div>
        </div>
        <hr/>
        <p class="copyright">Copyright &copy; 2021 - Red Store</p>
    </div>
</div>


</body>
</html>